-
  branches:
    only:
    - master

  before_build:
    - nuget restore NunitGo.sln

  build_script: 
    - msbuild NunitGo.sln /p:Configuration=Release /t:Rebuild
  
  test:
    categories:
      only:
        - SuccessCategory
